version: '3.9'
services:
    web:
        build: .
        restart: always
        ports:
            - "8000:5000"
        environment:
            - DEBUG=1
        networks:
            - flask_network
        depends_on:
            - db

    db:
        image: "postgres:14.2"
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: 1234
            POSTGRES_DB: "flask_db"
